# Generated by Django 3.1.7 on 2021-06-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20210602_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='cantidad_cervezas',
            field=models.IntegerField(null=True),
        ),
    ]
