# Generated by Django 3.1.7 on 2021-06-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20210606_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='hora',
            new_name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='fecha',
        ),
    ]
