# Generated by Django 3.1.7 on 2021-06-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20210606_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='meeting'),
        ),
    ]
