# Generated by Django 3.1.7 on 2021-06-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_meeting_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='cantidad_cervezas',
            new_name='cajas_birra',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='cantidad_invitados',
            new_name='invitados',
        ),
    ]
