# Generated by Django 3.1.7 on 2021-06-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210604_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='name',
        ),
    ]
